### ISSUE TITLE
Github Enterprise support

### ISSUE THREAD

**Issue by nickrivadeneira** [danielribeiro/github-diff-highlight-extension#14]
Github Enterprise is behind regular Github and doesn't have syntax highlighting support. It would be great if it could be configured to support it.

**Comment by danielribeiro** [comment]
Hi @nickrivadeneira. This project has been marked deprecated, since Github added the syntax highlight to github.com.

I've created a dev pre-release that may work for you though: https://github.com/danielribeiro/github-diff-highlight-extension/releases/tag/enable-on-github-enterprise-maybe-crx

It is based of this branch: https://github.com/danielribeiro/github-diff-highlight-extension/tree/enable-on-github-enterprise-maybe-with-crx

Install instructions for the .zip: http://www.howtogeek.com/120743/how-to-install-extensions-from-outside-the-chrome-web-store/ (read *zip* where he says *crx*, as it is just a filename).

The zip was created by calling .package on the branch above. The diff is simple: https://github.com/danielribeiro/github-diff-highlight-extension/pull/15/files

**Comment by danielribeiro** [comment]
Unfortunately, I'm not motivated to support github enterprise since I don't use it. Feel free to fork and change the project to suit you. I'm more glad to help you to make it work. If you wanna do so, I recommend going to the Chrome's doc, starting on how to install in dev mode: https://developer.chrome.com/extensions/getstarted#unpacked

Also, I recommend Extension reloader for a tighter feedback loop while developing : https://chrome.google.com/webstore/detail/extensions-reloader/fimgfedafeadlieiabdeeaodndnlbhid?hl=en

I had people successfully get this project working with github enterprise by doing a similar change to the manifest.
